import type { Product } from './types';

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Abstract Dreams',
    description: 'A vibrant abstract painting exploring the fluidity of dreams and subconscious thoughts. Features a rich color palette and dynamic brushstrokes.',
    price: 450,
    category: 'Painting',
    imageUrl: 'https://placehold.co/600x400.png',
    artist: 'Jane Doe',
    dimensions: '24x36 inches',
    medium: 'Oil on Canvas',
    dataAiHint: 'abstract painting',
  },
  {
    id: '2',
    name: 'Serene Landscape',
    description: 'A calming landscape painting depicting a misty morning in the mountains. Captures the tranquility and beauty of nature.',
    price: 320,
    category: 'Painting',
    imageUrl: 'https://placehold.co/600x400.png',
    artist: 'John Smith',
    dimensions: '18x24 inches',
    medium: 'Acrylic on Panel',
    dataAiHint: 'landscape painting',
  },
  {
    id: '3',
    name: 'Bronze Thinker',
    description: 'A modern bronze sculpture representing contemplation and introspection. Hand-cast with a unique patina finish.',
    price: 780,
    category: 'Sculpture',
    imageUrl: 'https://placehold.co/600x400.png',
    artist: 'Alex Johnson',
    dimensions: '15 inches high',
    medium: 'Bronze',
    dataAiHint: 'bronze sculpture',
  },
  {
    id: '4',
    name: 'Kinetic Motion',
    description: 'An intricate kinetic sculpture made of polished steel, creating mesmerizing patterns with gentle air currents.',
    price: 1200,
    category: 'Sculpture',
    imageUrl: 'https://placehold.co/600x400.png',
    artist: 'Emily White',
    dimensions: '30x30x10 inches',
    medium: 'Steel and Aluminum',
    dataAiHint: 'kinetic sculpture',
  },
  {
    id: '5',
    name: 'City Lights',
    description: 'A stunning photograph capturing the vibrant energy of a cityscape at night. Long exposure highlights the trails of light.',
    price: 150,
    category: 'Photography',
    imageUrl: 'https://placehold.co/600x400.png',
    artist: 'Michael Brown',
    dimensions: '16x20 inches print',
    medium: 'Archival Pigment Print',
    dataAiHint: 'cityscape photography',
  },
  {
    id: '6',
    name: 'Digital Bloom',
    description: 'A generative digital artwork showcasing intricate floral patterns that evolve over time. Presented on a high-resolution display.',
    price: 600,
    category: 'Digital Art',
    imageUrl: 'https://placehold.co/600x400.png',
    artist: 'Sarah Green',
    dimensions: 'Variable (Digital)',
    medium: 'Generative Algorithm',
    dataAiHint: 'digital art',
  },
];
